// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vibgoatjyvldsgyycfrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpYmdvYXRqeXZsZHNneXljZnJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTI1MTUsImV4cCI6MjA2NjE4ODUxNX0.m_6J8OuEXFmrB1iK6ZDEeV_SUWGfKi2E3B0BAXXJWB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);